# config.yaml

path:
  # Path to the cluster data
  cluster_path: ./data/external/mscluster

  # Path to the raw MGF files
  mgf_path: ./data/raw

  search_results:
    # Path and filename for de_novo search results
    de_novo:
      path: ./data/external/denovo
      filename: PXD014222_Casanovo.csv

    # Path and filename for database search results
    db:
      path: ./data/external/db
      filename: PXD014222_db.csv

  # Path to save project outputs
  save_path: ./data/interim

  # Path to the denoised MGF files
  denoised_mgf_path: ./data/processed/denoised_mgf

  # Path to the MGF files for cross-correlation calculations
  xcorr_mgf_path: ./data/processed/xcorr_mgf

  # Filename for the interim report
  interim_report: dataset_top2.csv
params:
  # Whether to train the model (True: training process, False: evaluation process)
  train: True

  # Whether to report the top 10 results (True: report top 10 candidate results, False: do not report)
  top_10: False
